### ISSUE TITLE
parseString errors on zero

### ISSUE THREAD

**Issue by Eiim** [alordash/parse-word-to-number#6]
parseString throws an error when trying to parse "zero".

```
> const { parseString } = require('@alordash/parse-word-to-number');
> parseString("zero")
Uncaught TypeError: Cannot read properties of undefined (reading 'text')
    at joinResult (C:\Users\ethan\node_modules\@alordash\parse-word-to-number\lib\parse-word-to-number.js:80:26)
    at parseString (C:\Users\ethan\node_modules\@alordash\parse-word-to-number\lib\parse-word-to-number.js:95:11)
```

**Comment by alordash** [comment]
Thank you for report. Fixed in [v3.0.7](https://github.com/alordash/parse-word-to-number/releases/tag/v3.0.7)
